name: Image-Lab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - aom=3.12.1=h7934f7d_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.0.2=py310hbf28c38_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - eigen=3.4.0=h4bd325d_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.33.3=py310h5764c6d_0
  - freetype=2.13.3=h4a9f257_0
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h48cff8f_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.12=hc146dc4_1
  - gstreamer=1.24.12=hb6d4d65_1
  - gstreamer-orc=0.4.41=h5eee18b_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.2=py310hbf28c38_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f98852_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=h46f56fc_0
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=h7f98852_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h28b3bda_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.29=h166bdaf_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.6=py310hff52083_1
  - matplotlib-base=3.10.6=py310h71dd3da_0
  - mesalib=25.1.5=h31e3550_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numpy=2.2.5=py310hc213724_2
  - numpy-base=2.2.5=py310hf387b04_2
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - opencv=4.10.0=py310h6030d24_7
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.7.3=py310hfe4ef28_1
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - qtbase=6.7.3=h10a5587_4
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtshadertools=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebengine=6.7.3=h5092597_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.1=py310h5764c6d_3
  - unicodedata2=14.0.0=py310h5764c6d_1
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.31=h516909a_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - awscli==1.44.5
      - boto3==1.42.10
      - botocore==1.42.15
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - cvdata==0.0.3
      - docutils==0.19
      - idna==3.11
      - jmespath==1.0.1
      - lxml==6.0.2
      - oidv6==1.0.5
      - opencv-contrib-python==4.12.0.88
      - pandas==2.3.3
      - progressbar2==4.5.0
      - pyasn1==0.6.1
      - python-utils==3.9.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rsa==4.7.2
      - s3transfer==0.16.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
prefix: /home/mengleang/anaconda3/envs/Image-Lab
